apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iyp1j467v-java-quarkus
  janus-idp.io/tekton: iyp1j467v-java-quarkus
  backstage.io/kubernetes-id: iyp1j467v-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iyp1j467v-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
